### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lukegorman** [ZigzagAK/ngx_amqp#2]
Extracting stream-lua-nginx-module.tar.gz
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- lua-cjson/Makefile	2016-11-07 08:47:47.000000000 +0300
|+++ lua-cjson/Makefile	2016-10-26 00:04:44.000000000 +0300
--------------------------

**Comment by ZigzagAK** [comment]
Fixed
